"""Regression tests for private owner context and canonical runtime inheritance."""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from wls.config import default_config
from wls.runtime import LivingSystem


def make_runtime(tmp_path: Path) -> LivingSystem:
    config = default_config(tmp_path / "home")
    config.sensors = []
    config.sleep_after_idle_cycles = 100
    return LivingSystem(config)


def entry(
    identity: str = "method-review", kind: str = "method",
    *, origin: str = "owner_direct", activate: bool = False,
    text: str = "Prefer verified evidence to self-reported completion.",
) -> dict:
    return {
        "id": identity, "kind": kind, "text": text,
        "origin": origin, "source_ref": "owner:current-dialogue",
        "activate_readonly": activate,
    }


def bundle(*entries: dict) -> dict:
    return {
        "schema": "wls.owner_context.v1",
        "consent": "owner_reviewed_local_import",
        "entries": list(entries),
    }


def write_bundle(runtime: LivingSystem, payload: dict) -> Path:
    path = runtime.owner_context.path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    return path


def test_no_bundle_does_not_claim_import(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    assert runtime.owner_context.import_pending()["status"] == "NO_LOCAL_BUNDLE"


def test_owner_context_import_is_idempotent_and_persists_across_restart(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bundle(
        entry(),
        entry("goal-wls", "goal", activate=True,
              text="Improve WLS learning by real task evidence"),
        entry("skill-evidence", "skill",
              text="Compare frozen baseline against independent held-out tasks"),
    ))
    result = runtime.owner_context.import_pending()
    assert result["status"] == "IMPORTED"
    assert result["imported"] == 3
    assert result["read_only_goals"] == 1
    assert result["declarative_skills_only"] is True
    assert runtime.owner_context.import_pending()["status"] == "UNCHANGED"
    remembered = runtime.memories.retrieve("verified evidence", limit=20)
    assert any(row["content"]["kind"] == "method" for row in remembered)
    assert len(runtime.goals.active()) == 1
    assert runtime.goals.active()[0].task_spec["proposal_only"] is True
    assert runtime.skills.active() == []
    restarted = LivingSystem(runtime.config)
    assert restarted.owner_context.import_pending()["status"] == "UNCHANGED"
    assert len(restarted.goals.active()) == 1
    assert restarted.db.query_one(
        "SELECT COUNT(*) AS n FROM memories WHERE active=1 AND memory_type='owner_context'"
    )["n"] == 3


def test_canonical_cycle_automatically_imports_only_local_owner_context(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bundle(entry(
        "goal-living", "goal", activate=True,
        text="Evaluate the persistent self-learning loop with real observations",
    )))
    assert runtime.db.query_one(
        "SELECT COUNT(*) AS n FROM memories WHERE memory_type='owner_context'"
    )["n"] == 0
    report = runtime.run_cycle()
    assert report["status"] == "SUCCEEDED"
    assert runtime.db.get_runtime("owner_context_last_import")["imported"] == 1
    assert len(runtime.goals.active()) == 1
    assert runtime.run_cycle()["status"] == "SUCCEEDED"
    assert runtime.owner_context.import_pending()["status"] == "UNCHANGED"


def test_unreviewed_chat_export_never_imports(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    data = bundle(entry())
    data["consent"] = "model_autogenerated"
    write_bundle(runtime, data)
    with pytest.raises(PermissionError):
        runtime.owner_context.import_pending()
    assert runtime.db.query_one("SELECT COUNT(*) AS n FROM memories")["n"] == 0


@pytest.mark.parametrize("bad", [
    bundle(entry("dup"), entry("dup", text="Changed")),
    bundle(entry("danger", "skill", activate=True)),
    bundle(entry("model-goal", "goal", origin="assistant_summary", activate=True)),
    bundle(entry("long", text="x" * 1501)),
    bundle(entry("../unsafe")),
])
def test_invalid_bundles_fail_closed_before_any_write(tmp_path: Path, bad: dict) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bad)
    with pytest.raises((ValueError, PermissionError)):
        runtime.owner_context.import_pending()
    assert runtime.db.query_one("SELECT COUNT(*) AS n FROM memories")["n"] == 0
    assert runtime.goals.active() == []


def test_one_invalid_entry_cannot_partially_import_prior_valid_entry(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bundle(entry("ok"), entry("bad", text="X" * 1501)))
    with pytest.raises(ValueError):
        runtime.owner_context.import_pending()
    assert runtime.db.query_one("SELECT COUNT(*) AS n FROM memories")["n"] == 0


def test_revision_requires_new_id_instead_of_silent_rewrite(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bundle(entry()))
    runtime.owner_context.import_pending()
    write_bundle(runtime, bundle(entry(text="A different apparent preference")))
    with pytest.raises(ValueError, match="new ID"):
        runtime.owner_context.import_pending()
    assert runtime.memories.retrieve("verified evidence", limit=20)[0]["content"]["text"].startswith("Prefer")


def test_symlink_and_oversized_owner_context_are_rejected(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    target = tmp_path / "other.json"
    target.write_text(json.dumps(bundle(entry())), encoding="utf-8")
    link = runtime.owner_context.path
    try:
        link.symlink_to(target)
    except (NotImplementedError, OSError):
        pytest.skip("symlinks not supported on this runner")
    with pytest.raises(ValueError, match="non-symlink"):
        runtime.owner_context.import_pending()
    link.unlink()
    link.write_bytes(b"x" * 512001)
    with pytest.raises(ValueError, match="byte limit"):
        runtime.owner_context.import_pending()


def test_bad_local_bundle_does_not_crash_life_cycle_or_disclose_content(tmp_path: Path) -> None:
    runtime = make_runtime(tmp_path)
    write_bundle(runtime, bundle(entry("not-approved", "goal", activate=True,
                                    origin="assistant_summary", text="PRIVATE PHRASE")))
    assert runtime.run_cycle()["status"] == "SUCCEEDED"
    receipt = runtime.db.get_runtime("owner_context_last_import")
    assert receipt == {"status": "REJECTED", "error_type": "PermissionError"}
    assert "PRIVATE PHRASE" not in json.dumps(receipt)
    assert runtime.db.query_one("SELECT COUNT(*) AS n FROM memories WHERE memory_type='owner_context'")["n"] == 0
